name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Generate
      run: go generate .

    - name: Build linux-amd64
      env:
        GOOS: linux
        GOARCH: amd64
      run: go build -v -ldflags='-s -w' -o reboot_watcher.linux.amd64 .

    - name: Build darwin-arm64
      env:
        GOOS: darwin
        GOARCH: arm64
      run: go build -v -ldflags='-s -w' -o reboot_watcher.darwin.arm64 .

    - name: Checksums
      run: sha256sum reboot_watcher.* > sha256sums.txt
g
    - name: Test
      run: go test -v ./...

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        files: |
          sha256sums.txt
          reboot_watcher.*
